cartasIniciales = [("Ardent Elementalist",1),
    ("Pyre Spawn", 1),
    ("Maw of Kozilek", 1),
    ("Reckless Bushwhacker", 2),
    ("Frontline War-Rager", 1),
    ("Hungry Ridgewolf", 2),
    ("Invasive Maneuvers", 1),
    ("Mayhem patrol", 1),
    ("Zookeeper Mechan", 2),
    ("Molecular Modifier", 1),
    ("Oreplate Pangolin", 1),
    ("Expedite", 3),
    ("Red Tiger Mechan", 1),
    ("Craven Hulk", 1),
    ("Kavaron Turbodron", 1),
    ("Unlucky witness", 1),
    ("Hemosymbic Mite", 1),
    ("Oakshade Stalker", 2),
    ("Arlinn, Voice of the Pack", 1),
    ("Harmonious Grovestrider", 1),
    ("Fungal Colossus", 1),
    ("Sami's Curiosity", 1),
    ("Lashwhip Predator", 1),
    ("Thawbringer", 2),
    ("Canopy Gorger", 1),
    ("Dawnhart Disciple", 3),
    ("Icecave Crasher", 1),
    ("Atmospheric Greenhouse", 2),
    ("Rhox Pummeler", 2),
    ("Hookhand Mariner", 1),
    ("Embodiment of Insight", 1),
    ("Intrepid Tenderfoot", 1),
    ("Gene Pollinator", 1),
    ("Sunbathing Rootwalla", 2),
    ("Vile Redeemer", 1),
    ("Edge Rover", 2),
    ("Galactic Wayfarer", 3),
    ("Bonds of Mortality", 1),
    ("Stalking Drone", 1),
    ("Spatial Contortion", 1),
    ("Space-Time Anomaly", 1),
    ("Exotic pets", 1),
    ("Siphon Insight", 2),
    ("Mm'menon, Uthros Exile", 1),
    ("Bloodtithe Harvester", 1),
    ("Fatal grudge", 1),
    ("Baloth Null", 1),
    ("Haliya, Ascendant Cadet", 2),
    ("Brokers Charm", 1),
    ("Infinite Guideline Station", 1),
    ("Pinnacle Kill-Ship", 2),
    ("Nutrient Block", 2),
    ("Chrome cat", 1),
    ("Chrome companion", 3),
    ("Commander's Sphere", 2),
    ("Wurmwall Sweeper", 1),
    ("Seer's Lantern", 2),
    ("Eldrazi mimic", 1),
    ("Warden of Geometries", 1),
    ("Blighted Gorge", 1),
    ("Command Bridge", 1),
    ("Scavenger Grounds", 1),
    ("Crumbling Vestige", 1),
    ("Rimewood Falls", 1),
    ("Deepfathom Skulker", 1),
    ("Roiling Waters", 1),
    ("Starbreach Whale", 1),
    ("Screaming Swarm", 1),
    ("Sinister Cryologist", 1),
    ("Ertai's Scorn", 2),
    ("Mahamoti Djinn", 1),
    ("Scrapskin Drake", 1),
    ("Umara Entangler", 1),
    ("Into the Void", 1),
    ("Emissary Escort", 1),
    ("Mechan Shieldmate", 1),
    ("Cloudsculpt Technician", 1),
    ("Steelclad Spirit", 1),
    ("Uthros Scanship", 1),
    ("Chill of the Grave", 1),
    ("Binding Geist", 1),
    ("Illvoi Galeblade", 1),
    ("Inga Rune-Eyes", 1),
    ("Abstruse Interference", 2),
    ("Cloud Manta", 2),
    ("Selfcraft Mechan", 1),
    ("Mental Modulation", 1),
    ("Berg Strider", 1),
    ("Mists of Littjara", 1),
    ("Gravity Negator", 1),
    ("Negate", 1),
    ("Steelswarm Operator", 1),
    ("Windrider Patrol", 1),
    ("Codecracker Hound", 2),
    ("Cyclone Sire", 1),
    ("Psionic Snoop", 1),
    ("Rune of flight", 1),
    ("Starwinder", 1),
    ("Weave Fate", 1),
    ("Cruel Witness", 1),
    ("Undercover Operative", 1),
    ("Jwar Isle Avenger", 2),
    ("Wanderlight Spirit", 1),
    ("Wingshield Agent", 1),
    ("All-Fates Stalker", 1),
    ("Dual-Sun Adeptus", 1),
    ("Eagle of the Watch", 1),
    ("Zealous Display", 2),
    ("Aegis Angel", 1),
    ("Apostle of Purifying Light", 4),
    ("Yoked Ox", 2),
    ("Scout for Survivors", 1),
    ("Akroan Jailer", 1),
    ("Sentinel of the Eternal Watch", 1),
    ("Codespell Cleric", 1),
    ("Dockworker Drone", 1),
    ("Pulsar Squadron Ace", 3),
    ("Sunstar Expansionist", 1),
    ("Brightspear Zealot", 1),
    ("Radiant Strike", 2),
    ("Hold for Ransom", 1),
    ("Heavy Infantry", 1),
    ("Piercing Light", 1),
    ("Luxknight Breacher", 2),
    ("Beyond the Quiet", 1),
    ("Weftblade Enhancer", 2),
    ("Starfighter Pilot", 1),
    ("Auxiliary Boosters", 2),
    ("Expedition Raptor", 1),
    ("Supernatural Rescue", 1),
    ("Revelation of Power", 1),
    ("Valor of the Worthy", 1),
    ("Valor in Akros", 1),
    ("Dawnstrike Vanguard", 1),
    ("Starport Security", 1),
    ("Parasitic Grasp", 3),
    ("Corpse Churn", 1),
    ("Alpharael, Stonechosen", 1),
    ("Cutthroat Contender", 1),
    ("Decode Transmissions", 2),
    ("Duress", 2),
    ("Dream Devourer", 1),
    ("Embrace Oblivion", 1),
    ("Monoist Sentry", 3),
    ("Infernal Grasp", 1),
    ("Kozilek's Translator", 2),
    ("Null Caller", 1),
    ("Join the Maestros", 1),
    ("Swarm Culler", 1),
    ("Perigee Beckoner", 2),
    ("Beamsaw Prospector", 1),
    ("Gravpack Monoist", 1),
    ("Courier Bat", 1),
    ("Dark Endurance", 1),
    ("Witness the End", 1),
    ("Ray of Enfeeblement", 2),
    ("Grisly Ritual", 1),
    ("Havoc Sower", 1),
    ("Vote Out", 2),
    ("Slaughter Drone", 1),
    ("Roving Actuator", 1),
    ("Kavaron Skywarden", 2),
    ("Territorial Bruntar", 2),
    ("Kav Landseeker", 1),
    ("Orbital Plunge", 1),
    ("Boulder Salvo", 1),
    ("Nebula Dragon", 1)]